apiVersion: v1
kind: Service
metadata:
  name: hashresponce-svc
  namespace: main-app
spec:
  type: NodePort
  selector:
    app: hashgenerator
  ports:
    - port: 2345
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-data
  namespace: main-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator
  namespace: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: common-data
          persistentVolumeClaim:
            claimName: common-data
      containers:
        - name: hashgenerator-server
          image: hkotka/main-app1
          imagePullPolicy: Always
          volumeMounts:
            - name: common-data
              mountPath: /common-data
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: main-app-configmap
                  key: MESSAGE
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "400m"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
        - name: timestamper
          image: hkotka/main-app2
          imagePullPolicy: Always
          volumeMounts:
            - name: common-data
              mountPath: /common-data
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "400m"
