apiVersion: v1
kind: Service
metadata:
  name: hashresponce-svc
spec:
  type: ClusterIP
  selector:
    app: hashgenerator
  ports:
    - port: 2345
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: common-data
          persistentVolumeClaim:
            claimName: data-share
      containers:
        - name: hashgenerator-server
          image: hkotka/main-app1
          imagePullPolicy: Always
          volumeMounts:
            - name: common-data
              mountPath: /common-data
        - name: timestamper
          image: hkotka/main-app2
          imagePullPolicy: Always
          volumeMounts:
            - name: common-data
              mountPath: /common-data