apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-data
  namespace: main-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
