apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-wiki-todo-cronjob
  namespace: project
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: project/cronjob
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-root-pw
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_URL
                  value: "postgres-project-svc"
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_USER
                  value: "postgres-admin"
                - name: POSTGRES_DB
                  value: "project"
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "200m"
                limits:
                  memory: "50Mi"
                  cpu: "400m"
          restartPolicy: OnFailure
