apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: project-backend
  ports:
    - port: 2348
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picsum
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-backend
  template:
    metadata:
      labels:
        app: project-backend
    spec:
      volumes:
        - name: picsum
          persistentVolumeClaim:
            claimName: picsum
      containers:
        - name: project-backend
          image: project/backend
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-root-pw
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              value: "postgres-project-svc"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres-admin"
            - name: POSTGRES_DB
              value: "project"
          volumeMounts:
            - name: picsum
              mountPath: /images
          resources:
            requests:
              memory: "32Mi"
              cpu: "200m"
            limits:
              memory: "50Mi"
              cpu: "400m"
